### ISSUE TITLE
When I send order parameter on index route it throws QueryException

### ISSUE THREAD

**Issue by inosjack** [Froiden/laravel-rest-api#1] opened 2016-09-17 10:03 UTC
> Request: 
> `$response = $this->call('GET', '/dummyUser',
>             [
>                 'order' => "id asc",
>             ]);
>         $this->assertEquals(200, $response->status());`
> 
> Response: 
> `<h1>Whoops, looks like something went wrong.</h1>\n                                                                                                       
>                                         <h2 class="block_exception clear_fix">\n                                                                                          
>                             <span class="exception_counter">2/2</span>\n                                                                                                  
>                             <span class="exception_title"><abbr title="Illuminate\Database\QueryException">QueryException</abbr> in <a title="E:\xampp\htdocs\september201
> 6\12september\vendor\laravel\framework\src\Illuminate\Database\Connection.php line 761" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Connecti
> on.php line 761</a>:</span>\n                                                                                                                                             
>                             <span class="exception_message">SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with
>  no GROUP columns is illegal if there is no GROUP BY clause (SQL: select count(`dummyUsers`.`id`) as aggregate from`dummyUsers`where (`age`&lt; 7) order by`id`asc li
> mit 5 offset 0)</span>\n                                                                                                                                                  
>                         </h2>\n                                                                                                                                           
>                         <div class="block">\n                                                                                                                             
>                             <ol class="traces list_exception">\n                                                                                                          
>        <li> in <a title="E:\xampp\htdocs\september2016\12september\vendor\laravel\framework\src\Illuminate\Database\Connection.php line 761" ondblclick="var f=this.innerH
> TML;this.innerHTML=this.title;this.title=f;">Connection.php line 761</a></li>\n                                                                                           
>        <li>at <abbr title="Illuminate\Database\Connection">Connection</abbr>-`

**Comment by shashankkrjain** [comment] 2016-10-01 09:34
Not being able to reproduce the issue. Can you please write a test case for it?

**Comment by shashankkrjain** [comment] 2016-10-02 13:53
Closing as cannot reproduce

**Closed as completed by shashankkrjain** 2016-10-02 13:53 UTC
